version: '3'
services:

  postgres:
    image: dexels/dvdrental:1
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: mysecretpassword

  navajo:
    build:
      context: .
      args:
        VERSION: ${VERSION}
    ports:
      - "8181:8181"
    environment:
     - CLUSTER=demo
     - CONSOLE_PASS={sha-256}jGl25bVBBBW96Qi9Te4V37Fnqchz/Eu4qB9vKrRIqRg=
     - CONSOLE_USER=admin
     - FILE_REPOSITORY_DEPLOYMENT=develop
     - HAZELCAST_SIMPLE=true
     - INSTANCENAME=instance-1
     - LOGAPPENDERS=out,stdout
     - NAVAJO_REQUEST_TIMEOUT=5000
     - NO_DBREPLICATION=true
     - NO_DBTRIGGER=true
     - TENANT_MASTER=Tenant1
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8181/status || exit 1"]
      interval: 1m00s
      timeout: 10s
      retries: 3

  mongodemo:
    image: mongo:latest
    ports:
      - "27017:27017"

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka0:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 10.0.0.86
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  kafka1:
    image: wurstmeister/kafka
    ports:
      - "9093:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 10.0.0.86
      KAFKA_ADVERTISED_PORT: 9093
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  kafka2:
    image: wurstmeister/kafka
    ports:
      - "9094:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 10.0.0.86
      KAFKA_ADVERTISED_PORT: 9094
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

