version: '2'
services:
  postgres:
    image: dexels/dvdrental:0.1.5
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: mysecretpassword
  mongo:
    image: mongo:latest
    environment:
      - MONGO_DATA_DIR=/data/db
    ports:
      - 27017:27017
    command: mongod --smallfiles # --quiet
  navajo:
    image: dexels/navajo-demo:1
    ports:
      - "8181:8181"
    environment:
     - CLUSTER=demo
     - HAZELCAST_SIMPLE=true
     - FILE_REPOSITORY_DEPLOYMENT=develop
