version: '2.2'
services:
  postgres:
    image: dexels/dvdrental:1
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: mysecretpassword
  navajo:
    build:
      context: .
      args:
        VERSION: latest
    ports:
      - "8181:8181"
    environment:
     - CLUSTER=demo
     - HAZELCAST_SIMPLE=true
     - FILE_REPOSITORY_DEPLOYMENT=develop
  mongodemo:
    image: debezium/example-mongodb:latest
    ports:
      - "27017:27017"
