version: 2
jobs:
  build:
    machine:
      image: circleci/classic:edge
    steps:
      - checkout
      - run: |
          docker --version
          docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run: |
          pwd
          ls -l
          MINORTAG=0.1
          IMAGE=dexels/navajo.example
          BASEBUILDNR=$(curl -s "https://circleci.com/api/v1.1/project/github/Dexels/navajo-platform?circle-token=${CIRCLE_TOKEN}&offset=0&filter=successful" | jq '[.[]| select(.workflows.job_name == "package_navajo")][0].build_num')          
          BASETAG=${MINORTAG}.$BASEBUILDNR
          echo "Tagging for: ${IMAGE}:${MINORTAG}.${CIRCLE_BUILD_NUM}  dexels/navajo.example:${BASETAG} onto super: ${BASETAG}"
          docker build . --build-arg VERSION=${BASETAG} -t ${IMAGE}:${MINORTAG}.${CIRCLE_BUILD_NUM} -t ${IMAGE}:latest
          docker push ${IMAGE}:${MINORTAG}.${CIRCLE_BUILD_NUM}
          docker push ${IMAGE}:latest
  test:
    machine:
      image: circleci/classic:edge
    steps:
      - checkout
      - run: |
          curl --version
          apt-get -y install jq
          curl -s -XGET -H "Authorization: Basic YTph" -H "X-Navajo-Instance: Tenant1" -H "Accept: application/json" -H "X-Navajo-Version: 0" "http://localhost:8181/entity/movie/ActorList"
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker-compose up -d
          sleep 10
          FIRSTACTOR=$('curl -s -XGET -H "Authorization: Basic YTph" -H "X-Navajo-Instance: Tenant1" -H "Accept: application/json" -H "X-Navajo-Version: 0" "http://localhost:8181/entity/movie/ActorList" | jq .Actor[0].LastName')
          echo "FirstActor: $FIRSTACTOR"
          
workflows:
  version: 2
  workflow:
    jobs:
      - build
      - test:
          requires:
            - build
