version: 2.1
jobs:

  test:
    docker:
      - image: cimg/base:stable
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASS
    steps:
      - checkout

      # See https://circleci.com/docs/2.0/building-docker-images/
      - setup_remote_docker:
          version: 19.03.13

      - run:
          name: Log in with docker registries
          command: |
            docker --version
            echo $DOCKERHUB_PASS | docker login --username $DOCKERHUB_USER --password-stdin

      - run:
          name: Build Docker Compose environment & run tests
          command: |
            SUFFIX=`[[ "${CIRCLE_BRANCH}" = "master" ]] && echo "" || echo "-${CIRCLE_BRANCH}"`
            export BASE_VERSION=$(curl -s "https://circleci.com/api/v1.1/project/github/Dexels/navajo-container?circle-token=${CIRCLE_TOKEN}&limit=100&offset=0&filter=successful" | jq "[.[]| select(.workflows.job_name == \"build\" and .branch == \"${CIRCLE_BRANCH}\")][0].build_num")
            export MINORVERSION=3.3
            export VERSION=${MINORVERSION}.${BASE_VERSION}${SUFFIX}
            docker-compose up -d
            echo "Compose completed"
            date
            sleep 60
            echo "Sleep completed at:"
            date
            mkdir /tmp/surefire-reports
            docker run -v /tmp/surefire-reports:/surefire-reports -e URL=http://navajo:8181 --network project_default dexels/navajo.example.test:latest
      - store_test_results:
          # Upload test results for display in Test Summary: https://circleci.com/docs/2.0/collect-test-data/
          path: /tmp/surefire-reports

workflows:
  version: 2
  workflow:
    jobs:
      - test:
          context:
          - dexels_docker_hub

