version: 2
jobs:
  build:
    machine:
      image: circleci/classic:edge
    steps:
      - checkout
      - run: |
          docker --version
          docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run: |
          pwd
          ls -l
          MINORTAG=0.1
          BASEBUILDNR=$(curl -s "https://circleci.com/api/v1.1/project/github/Dexels/navajo-platform?circle-token=${CIRCLE_TOKEN}&offset=0&filter=successful" | jq '[.[]| select(.workflows.job_name == "package_navajo")][0].build_num')
          TAG=${CIRCLE_BUILD_NUM}
          BASETAG=${MINORTAG}.$BASEBUILDNR
          echo "Tagging for: ${TAG}  dexels/navajo.example:${BASETAG} passing version: ${BASETAG}"
          docker build . --build-arg VERSION=${BASETAG} -t dexels/navajo.example:$BASETAG -t dexels/navajo.example:latest
          docker push dexels/navajo.example:$TAG
          docker push dexels/navajo.example:latest
workflows:
  version: 2
  workflow:
    jobs:
      - build
