version: 2
jobs:
  build:
    machine:
      image: circleci/classic:edge
    steps:
      - checkout
      - run: |
          docker --version
          docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run: |
          pwd
          ls -l
          MINORTAG=0.1
          IMAGE=dexels/navajo.example
          BASEBUILDNR=$(curl -s "https://circleci.com/api/v1.1/project/github/Dexels/navajo-platform?circle-token=${CIRCLE_TOKEN}&offset=0&filter=successful" | jq '[.[]| select(.workflows.job_name == "package_navajo")][0].build_num')          
          BASETAG=${MINORTAG}.$BASEBUILDNR
          echo "Tagging for: ${IMAGE}:${MINORTAG}.${CIRCLE_BUILD_NUM}  dexels/navajo.example:${BASETAG} onto super: ${BASETAG}"
          docker build . --build-arg VERSION=${BASETAG} -t ${IMAGE}:${MINORTAG}.${CIRCLE_BUILD_NUM} -t ${IMAGE}:latest
          docker push ${IMAGE}:${MINORTAG}.${CIRCLE_BUILD_NUM}
          docker push ${IMAGE}:latest
  test:
    machine:
      image: circleci/classic:edge
    steps:
      - checkout
      - run: |
          echo 'current dir: '
          pwd
          curl --version
          JQ_URL="https://circle-downloads.s3.amazonaws.com/circleci-images/cache/linux-amd64/jq-latest"
          curl --show-error --location --fail --retry 3 --output ./jq $JQ_URL
          chmod +x ./jq
          ./jq --version
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker-compose up -d
          echo "Compose completed"
          sleep 100
          echo "Sleep completed"
          curl --retry 10 --retry-delay 5 -XGET -H "Authorization: Basic YTph" -H "X-Navajo-Instance: Tenant1" -H "Accept: application/json" -H "X-Navajo-Version: 0" "http://localhost:8181/entity/movie/ActorList"
          echo "second, pipe to jq:"
          curl --retry 10 --retry-delay 5 -XGET -H "Authorization: Basic YTph" -H "X-Navajo-Instance: Tenant1" -H "Accept: application/json" -H "X-Navajo-Version: 0" "http://localhost:8181/entity/movie/ActorList" | ./jq
          FIRSTACTOR=$('curl --retry 10 --retry-delay 5 -s -XGET -H "Authorization: Basic YTph" -H "X-Navajo-Instance: Tenant1" -H "Accept: application/json" -H "X-Navajo-Version: 0" "http://localhost:8181/entity/movie/ActorList" | jq .Actor[0].LastName')
          echo "FirstActor: $FIRSTACTOR"
          
workflows:
  version: 2
  workflow:
    jobs:
      - build
      - test:
          requires:
            - build
